accenture:
  path: /accenture-interactive
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /ncaevents/accenture-interactive
    permanent: true
hof:
  path: /hall-of-fame
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /ncaevents/hall-of-fame
    permanent: true
influencerdb:
  path: /influencerdb
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /ncaevents/influencerdb
    permanent: true
otto:
  path: /otto
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /ncaevents/otto
    permanent: true
apollo:
  path: /apollo
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /ncaevents/apollo
    permanent: true
