#index:
#    path: /
#    controller: App\Controller\DefaultController::index

klp_mcp_server:
    resource: '@KlpMcpServerBundle/Resources/config/routes.php'
    type: php

mcp_oauth:
    resource: App\Controller\McpOAuthController
    type: attribute
